// Copyright (c) 2020 Pawel Maslanka
// Contact: pawmas.pawelmaslanka@gmail.com
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0-devel
// 	protoc        v3.11.0
// source: interfaces/aggregate.proto

package interfaces

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AggregateIntf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname string `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
}

func (x *AggregateIntf) Reset() {
	*x = AggregateIntf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_aggregate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateIntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateIntf) ProtoMessage() {}

func (x *AggregateIntf) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_aggregate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateIntf.ProtoReflect.Descriptor instead.
func (*AggregateIntf) Descriptor() ([]byte, []int) {
	return file_interfaces_aggregate_proto_rawDescGZIP(), []int{0}
}

func (x *AggregateIntf) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

type CreateAggregateIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIntf *AggregateIntf `protobuf:"bytes,1,opt,name=aggIntf,proto3" json:"aggIntf,omitempty"`
}

func (x *CreateAggregateIntfRequest) Reset() {
	*x = CreateAggregateIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_aggregate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAggregateIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAggregateIntfRequest) ProtoMessage() {}

func (x *CreateAggregateIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_aggregate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAggregateIntfRequest.ProtoReflect.Descriptor instead.
func (*CreateAggregateIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_aggregate_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAggregateIntfRequest) GetAggIntf() *AggregateIntf {
	if x != nil {
		return x.AggIntf
	}
	return nil
}

type DeleteAggregateIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIntf *AggregateIntf `protobuf:"bytes,1,opt,name=aggIntf,proto3" json:"aggIntf,omitempty"`
}

func (x *DeleteAggregateIntfRequest) Reset() {
	*x = DeleteAggregateIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_aggregate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAggregateIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAggregateIntfRequest) ProtoMessage() {}

func (x *DeleteAggregateIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_aggregate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAggregateIntfRequest.ProtoReflect.Descriptor instead.
func (*DeleteAggregateIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_aggregate_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAggregateIntfRequest) GetAggIntf() *AggregateIntf {
	if x != nil {
		return x.AggIntf
	}
	return nil
}

type AddEthernetIntfToAggregateIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIntf  *AggregateIntf  `protobuf:"bytes,1,opt,name=aggIntf,proto3" json:"aggIntf,omitempty"`
	EthIntfs []*EthernetIntf `protobuf:"bytes,2,rep,name=ethIntfs,proto3" json:"ethIntfs,omitempty"`
}

func (x *AddEthernetIntfToAggregateIntfRequest) Reset() {
	*x = AddEthernetIntfToAggregateIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_aggregate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEthernetIntfToAggregateIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEthernetIntfToAggregateIntfRequest) ProtoMessage() {}

func (x *AddEthernetIntfToAggregateIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_aggregate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEthernetIntfToAggregateIntfRequest.ProtoReflect.Descriptor instead.
func (*AddEthernetIntfToAggregateIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_aggregate_proto_rawDescGZIP(), []int{3}
}

func (x *AddEthernetIntfToAggregateIntfRequest) GetAggIntf() *AggregateIntf {
	if x != nil {
		return x.AggIntf
	}
	return nil
}

func (x *AddEthernetIntfToAggregateIntfRequest) GetEthIntfs() []*EthernetIntf {
	if x != nil {
		return x.EthIntfs
	}
	return nil
}

type RemoveEthernetIntfFromAggregateIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggIntf  *AggregateIntf  `protobuf:"bytes,1,opt,name=aggIntf,proto3" json:"aggIntf,omitempty"`
	EthIntfs []*EthernetIntf `protobuf:"bytes,2,rep,name=ethIntfs,proto3" json:"ethIntfs,omitempty"`
}

func (x *RemoveEthernetIntfFromAggregateIntfRequest) Reset() {
	*x = RemoveEthernetIntfFromAggregateIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_aggregate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveEthernetIntfFromAggregateIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEthernetIntfFromAggregateIntfRequest) ProtoMessage() {}

func (x *RemoveEthernetIntfFromAggregateIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_aggregate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEthernetIntfFromAggregateIntfRequest.ProtoReflect.Descriptor instead.
func (*RemoveEthernetIntfFromAggregateIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_aggregate_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveEthernetIntfFromAggregateIntfRequest) GetAggIntf() *AggregateIntf {
	if x != nil {
		return x.AggIntf
	}
	return nil
}

func (x *RemoveEthernetIntfFromAggregateIntfRequest) GetEthIntfs() []*EthernetIntf {
	if x != nil {
		return x.EthIntfs
	}
	return nil
}

var File_interfaces_aggregate_proto protoreflect.FileDescriptor

var file_interfaces_aggregate_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x1a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x74, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x61, 0x67,
	0x67, 0x49, 0x6e, 0x74, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x07, 0x61, 0x67, 0x67, 0x49, 0x6e, 0x74, 0x66, 0x22,
	0x51, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x07, 0x61, 0x67, 0x67, 0x49, 0x6e, 0x74, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x07, 0x61, 0x67, 0x67, 0x49, 0x6e,
	0x74, 0x66, 0x22, 0x92, 0x01, 0x0a, 0x25, 0x41, 0x64, 0x64, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x54, 0x6f, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07,
	0x61, 0x67, 0x67, 0x49, 0x6e, 0x74, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x07, 0x61, 0x67, 0x67, 0x49, 0x6e, 0x74,
	0x66, 0x12, 0x34, 0x0a, 0x08, 0x65, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x08, 0x65,
	0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x2a, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x46, 0x72,
	0x6f, 0x6d, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x61, 0x67, 0x67, 0x49, 0x6e, 0x74,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x74, 0x66, 0x52, 0x07, 0x61, 0x67, 0x67, 0x49, 0x6e, 0x74, 0x66, 0x12, 0x34, 0x0a, 0x08, 0x65,
	0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x08, 0x65, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x66,
	0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x6f, 0x70, 0x65, 0x6e, 0x6e, 0x6f, 0x73, 0x2d, 0x65, 0x74, 0x68,
	0x2d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x50,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interfaces_aggregate_proto_rawDescOnce sync.Once
	file_interfaces_aggregate_proto_rawDescData = file_interfaces_aggregate_proto_rawDesc
)

func file_interfaces_aggregate_proto_rawDescGZIP() []byte {
	file_interfaces_aggregate_proto_rawDescOnce.Do(func() {
		file_interfaces_aggregate_proto_rawDescData = protoimpl.X.CompressGZIP(file_interfaces_aggregate_proto_rawDescData)
	})
	return file_interfaces_aggregate_proto_rawDescData
}

var file_interfaces_aggregate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_interfaces_aggregate_proto_goTypes = []interface{}{
	(*AggregateIntf)(nil),                              // 0: interfaces.AggregateIntf
	(*CreateAggregateIntfRequest)(nil),                 // 1: interfaces.CreateAggregateIntfRequest
	(*DeleteAggregateIntfRequest)(nil),                 // 2: interfaces.DeleteAggregateIntfRequest
	(*AddEthernetIntfToAggregateIntfRequest)(nil),      // 3: interfaces.AddEthernetIntfToAggregateIntfRequest
	(*RemoveEthernetIntfFromAggregateIntfRequest)(nil), // 4: interfaces.RemoveEthernetIntfFromAggregateIntfRequest
	(*EthernetIntf)(nil),                               // 5: interfaces.EthernetIntf
}
var file_interfaces_aggregate_proto_depIdxs = []int32{
	0, // 0: interfaces.CreateAggregateIntfRequest.aggIntf:type_name -> interfaces.AggregateIntf
	0, // 1: interfaces.DeleteAggregateIntfRequest.aggIntf:type_name -> interfaces.AggregateIntf
	0, // 2: interfaces.AddEthernetIntfToAggregateIntfRequest.aggIntf:type_name -> interfaces.AggregateIntf
	5, // 3: interfaces.AddEthernetIntfToAggregateIntfRequest.ethIntfs:type_name -> interfaces.EthernetIntf
	0, // 4: interfaces.RemoveEthernetIntfFromAggregateIntfRequest.aggIntf:type_name -> interfaces.AggregateIntf
	5, // 5: interfaces.RemoveEthernetIntfFromAggregateIntfRequest.ethIntfs:type_name -> interfaces.EthernetIntf
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_interfaces_aggregate_proto_init() }
func file_interfaces_aggregate_proto_init() {
	if File_interfaces_aggregate_proto != nil {
		return
	}
	file_interfaces_ethernet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_interfaces_aggregate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateIntf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_aggregate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAggregateIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_aggregate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAggregateIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_aggregate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEthernetIntfToAggregateIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_aggregate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveEthernetIntfFromAggregateIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interfaces_aggregate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interfaces_aggregate_proto_goTypes,
		DependencyIndexes: file_interfaces_aggregate_proto_depIdxs,
		MessageInfos:      file_interfaces_aggregate_proto_msgTypes,
	}.Build()
	File_interfaces_aggregate_proto = out.File
	file_interfaces_aggregate_proto_rawDesc = nil
	file_interfaces_aggregate_proto_goTypes = nil
	file_interfaces_aggregate_proto_depIdxs = nil
}
