// Copyright (c) 2020 Pawel Maslanka
// Contact: pawmas.pawelmaslanka@gmail.com
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0-devel
// 	protoc        v3.11.0
// source: interfaces/ethernet.proto

package interfaces

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EthernetIntf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname string `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
}

func (x *EthernetIntf) Reset() {
	*x = EthernetIntf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_ethernet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthernetIntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthernetIntf) ProtoMessage() {}

func (x *EthernetIntf) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_ethernet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthernetIntf.ProtoReflect.Descriptor instead.
func (*EthernetIntf) Descriptor() ([]byte, []int) {
	return file_interfaces_ethernet_proto_rawDescGZIP(), []int{0}
}

func (x *EthernetIntf) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

type AddIpv4AddrToEthernetIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthIntf *EthernetIntf `protobuf:"bytes,1,opt,name=ethIntf,proto3" json:"ethIntf,omitempty"`
	Addr    *Ipv4Addr     `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *AddIpv4AddrToEthernetIntfRequest) Reset() {
	*x = AddIpv4AddrToEthernetIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_ethernet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIpv4AddrToEthernetIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIpv4AddrToEthernetIntfRequest) ProtoMessage() {}

func (x *AddIpv4AddrToEthernetIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_ethernet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIpv4AddrToEthernetIntfRequest.ProtoReflect.Descriptor instead.
func (*AddIpv4AddrToEthernetIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_ethernet_proto_rawDescGZIP(), []int{1}
}

func (x *AddIpv4AddrToEthernetIntfRequest) GetEthIntf() *EthernetIntf {
	if x != nil {
		return x.EthIntf
	}
	return nil
}

func (x *AddIpv4AddrToEthernetIntfRequest) GetAddr() *Ipv4Addr {
	if x != nil {
		return x.Addr
	}
	return nil
}

type RemoveIpv4AddrFromEthernetIntfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthIntf *EthernetIntf `protobuf:"bytes,1,opt,name=ethIntf,proto3" json:"ethIntf,omitempty"`
	Addr    *Ipv4Addr     `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RemoveIpv4AddrFromEthernetIntfRequest) Reset() {
	*x = RemoveIpv4AddrFromEthernetIntfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_ethernet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIpv4AddrFromEthernetIntfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIpv4AddrFromEthernetIntfRequest) ProtoMessage() {}

func (x *RemoveIpv4AddrFromEthernetIntfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_ethernet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIpv4AddrFromEthernetIntfRequest.ProtoReflect.Descriptor instead.
func (*RemoveIpv4AddrFromEthernetIntfRequest) Descriptor() ([]byte, []int) {
	return file_interfaces_ethernet_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIpv4AddrFromEthernetIntfRequest) GetEthIntf() *EthernetIntf {
	if x != nil {
		return x.EthIntf
	}
	return nil
}

func (x *RemoveIpv4AddrFromEthernetIntfRequest) GetAddr() *Ipv4Addr {
	if x != nil {
		return x.Addr
	}
	return nil
}

var File_interfaces_ethernet_proto protoreflect.FileDescriptor

var file_interfaces_ethernet_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x74, 0x68,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0c, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80,
	0x01, 0x0a, 0x20, 0x41, 0x64, 0x64, 0x49, 0x70, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x54, 0x6f,
	0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x07,
	0x65, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x22, 0x85, 0x01, 0x0a, 0x25, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x70, 0x76, 0x34,
	0x41, 0x64, 0x64, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x65,
	0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x66, 0x52, 0x07, 0x65, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x66, 0x12,
	0x28, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x49, 0x70, 0x76, 0x34, 0x41,
	0x64, 0x64, 0x72, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x42, 0x2c, 0x5a, 0x2a, 0x6f, 0x70, 0x65,
	0x6e, 0x6e, 0x6f, 0x73, 0x2d, 0x65, 0x74, 0x68, 0x2d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_interfaces_ethernet_proto_rawDescOnce sync.Once
	file_interfaces_ethernet_proto_rawDescData = file_interfaces_ethernet_proto_rawDesc
)

func file_interfaces_ethernet_proto_rawDescGZIP() []byte {
	file_interfaces_ethernet_proto_rawDescOnce.Do(func() {
		file_interfaces_ethernet_proto_rawDescData = protoimpl.X.CompressGZIP(file_interfaces_ethernet_proto_rawDescData)
	})
	return file_interfaces_ethernet_proto_rawDescData
}

var file_interfaces_ethernet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_interfaces_ethernet_proto_goTypes = []interface{}{
	(*EthernetIntf)(nil),                          // 0: interfaces.EthernetIntf
	(*AddIpv4AddrToEthernetIntfRequest)(nil),      // 1: interfaces.AddIpv4AddrToEthernetIntfRequest
	(*RemoveIpv4AddrFromEthernetIntfRequest)(nil), // 2: interfaces.RemoveIpv4AddrFromEthernetIntfRequest
	(*Ipv4Addr)(nil),                              // 3: interfaces.Ipv4Addr
}
var file_interfaces_ethernet_proto_depIdxs = []int32{
	0, // 0: interfaces.AddIpv4AddrToEthernetIntfRequest.ethIntf:type_name -> interfaces.EthernetIntf
	3, // 1: interfaces.AddIpv4AddrToEthernetIntfRequest.addr:type_name -> interfaces.Ipv4Addr
	0, // 2: interfaces.RemoveIpv4AddrFromEthernetIntfRequest.ethIntf:type_name -> interfaces.EthernetIntf
	3, // 3: interfaces.RemoveIpv4AddrFromEthernetIntfRequest.addr:type_name -> interfaces.Ipv4Addr
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_interfaces_ethernet_proto_init() }
func file_interfaces_ethernet_proto_init() {
	if File_interfaces_ethernet_proto != nil {
		return
	}
	file_interfaces_subinterface_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_interfaces_ethernet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthernetIntf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_ethernet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIpv4AddrToEthernetIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaces_ethernet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIpv4AddrFromEthernetIntfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interfaces_ethernet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interfaces_ethernet_proto_goTypes,
		DependencyIndexes: file_interfaces_ethernet_proto_depIdxs,
		MessageInfos:      file_interfaces_ethernet_proto_msgTypes,
	}.Build()
	File_interfaces_ethernet_proto = out.File
	file_interfaces_ethernet_proto_rawDesc = nil
	file_interfaces_ethernet_proto_goTypes = nil
	file_interfaces_ethernet_proto_depIdxs = nil
}
