// Copyright (c) 2020 Pawel Maslanka
// Contact: pawmas.pawelmaslanka@gmail.com
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0-devel
// 	protoc        v3.11.0
// source: interfaces/subinterface.proto

package interfaces

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ipv4Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PrfxLen uint32 `protobuf:"varint,2,opt,name=prfxLen,proto3" json:"prfxLen,omitempty"`
}

func (x *Ipv4Addr) Reset() {
	*x = Ipv4Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaces_subinterface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv4Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv4Addr) ProtoMessage() {}

func (x *Ipv4Addr) ProtoReflect() protoreflect.Message {
	mi := &file_interfaces_subinterface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv4Addr.ProtoReflect.Descriptor instead.
func (*Ipv4Addr) Descriptor() ([]byte, []int) {
	return file_interfaces_subinterface_proto_rawDescGZIP(), []int{0}
}

func (x *Ipv4Addr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Ipv4Addr) GetPrfxLen() uint32 {
	if x != nil {
		return x.PrfxLen
	}
	return 0
}

var File_interfaces_subinterface_proto protoreflect.FileDescriptor

var file_interfaces_subinterface_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x75, 0x62,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x08, 0x49,
	0x70, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x66, 0x78, 0x4c,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x72, 0x66, 0x78, 0x4c, 0x65,
	0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x6f, 0x70, 0x65, 0x6e, 0x6e, 0x6f, 0x73, 0x2d, 0x65, 0x74, 0x68,
	0x2d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interfaces_subinterface_proto_rawDescOnce sync.Once
	file_interfaces_subinterface_proto_rawDescData = file_interfaces_subinterface_proto_rawDesc
)

func file_interfaces_subinterface_proto_rawDescGZIP() []byte {
	file_interfaces_subinterface_proto_rawDescOnce.Do(func() {
		file_interfaces_subinterface_proto_rawDescData = protoimpl.X.CompressGZIP(file_interfaces_subinterface_proto_rawDescData)
	})
	return file_interfaces_subinterface_proto_rawDescData
}

var file_interfaces_subinterface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_interfaces_subinterface_proto_goTypes = []interface{}{
	(*Ipv4Addr)(nil), // 0: interfaces.Ipv4Addr
}
var file_interfaces_subinterface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interfaces_subinterface_proto_init() }
func file_interfaces_subinterface_proto_init() {
	if File_interfaces_subinterface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interfaces_subinterface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv4Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interfaces_subinterface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interfaces_subinterface_proto_goTypes,
		DependencyIndexes: file_interfaces_subinterface_proto_depIdxs,
		MessageInfos:      file_interfaces_subinterface_proto_msgTypes,
	}.Build()
	File_interfaces_subinterface_proto = out.File
	file_interfaces_subinterface_proto_rawDesc = nil
	file_interfaces_subinterface_proto_goTypes = nil
	file_interfaces_subinterface_proto_depIdxs = nil
}
